### ISSUE TITLE
Enable API token access for Zenhub and Jira

### ISSUE THREAD

**Issue by mjkrause** [ucsc-cgp/sync-agile-boards#4]
Related to #TLP-838

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SAB-1)
┆Project Name: sync-agile-boards
┆Issue Number: SAB-1

**Comment by bencvdb** [comment]
@mjkrause This is ready to be closed, right?

**Comment by mjkrause** [comment]
We should check with @Emily Soth <esoth@ucsc.edu>. AFIAK she found that
Jira access requires the user name, and base64 enconding into a token. That
should be part of that ticket.
