### ISSUE TITLE
Add two use cases for sprint synchronization

### ISSUE THREAD

**Issue by mjkrause** [ucsc-cgp/sync-agile-boards#80]
Two use cases are not covered by unit tests following PR #72. This applies to corresponding tickets in ZenHub and Jira to be synchronized from ZenHub to Jira:

- [x] the value of key Milestone of the ZenHub/GitHub ticket is `None` but the corresponding Jira ticket is associated with a sprint

- [x] the value (string) of the Milestone key of a ZenHub/GitHub ticket does not match the string of the corresponding Jira sprint name

- [x] if a ticket in the master system is associated with a different sprint than it is in the slave system, but a sprint with that name exists in the slave system, then associate that ticket in slave with same sprint as it is associated with in master

- [x] if a ticket in the master system is associated with a different sprint than it is in the slave system, but slave does not contain a sprint with that name then, take no action and continue with iteration (in line with what is specified in #49)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SAB-44)
┆Project Name: sync-agile-boards
┆Issue Number: SAB-44

**Comment by cricketsloan** [comment]
> ➤ Stefan Kuhn commented:
> 
> Should Michael B be the Reviewer in Cricket’s absence?

If this is not resolved today.  We can hand it to Michael B.  I am about to review now.
